### PR TITLE
Escape single quotes in the code output

### LINKED ISSUE #14: need escaping in the output example
If you use quotation marks as an alphabet, you will get an incorrect source code at the output

### PR DESCRIPTION
**Pull request by chuck-sys**
Closes #14.

### CODE REVIEW

File: src/nano_id_cc/core.cljs [hunk 1]
```diff
@@ -4,6 +4,7 @@
             [nano-id-cc.calc :as calc]
             [nano-id-cc.elements :as elements]
             [nano-id-cc.defaults :as defaults]
+            [clojure.string :as st]
```
Comment (zelark) [inline src/nano_id_cc/core.cljs]: Please, replace `st` with `string`. It will improve readability.
If you want more on it, check out http://tonsky.me/blog/readable-clojure/.

File: src/nano_id_cc/core.cljs [hunk 2]
```diff
@@ -49,17 +50,23 @@
     (str (format-time time))))
 
 
+(defn escape
```
Comment (zelark) [inline src/nano_id_cc/core.cljs]: Because we don't care about double quotes, it can be simplified. So the final function could be as follow: 
```clojure
(defn escape [s] (string/escape s {\' "\\'"}))
```

File: src/nano_id_cc/core.cljs [hunk 3]
```diff
@@ -49,17 +50,23 @@
...
+                \" "\\\""}))
+
+
 (defn code-sample
   [{:keys [alphabet length]}]
   (let [custom? (not= alphabet defaults/alphabet)
         len     (when (not= length defaults/length) length)
         nano-id (nano-id.custom/generate alphabet)
-        id      (nano-id length)]
+        id      (escape (nano-id length))]
```
Comment (zelark) [inline src/nano_id_cc/core.cljs]: Because `id` represents a string as it is, we shouldn't care about escaping here. Moreover it's just a comment.

**Review by zelark — CHANGES_REQUESTED** [review]

**Review by zelark — APPROVED** [review]

**Comment by zelark** [comment]
Thanks.
